/* Écoute — all the teaching content, and nothing else.

   Split out of french-sounds.html so the material can be edited without reading
   a line of app code: add a minimal pair here and the course picks it up on its
   own (the `focus` field IS the lesson id — see contrastKey() in the app).

   Loaded as a plain classic script before the app, so everything below is a
   global. No build step, no imports, nothing to compile. */


/* ===========================================================
   DATA — every French vowel phoneme is covered across the set.
   Oral:  i y u e ɛ ø œ ə a o ɔ
   Nasal: ɑ̃ ɛ̃ ɔ̃ œ̃
   Each item: prompt (what is spoken), options, answer index, focus, ipa
   =========================================================== */

const LEVEL1 = [
  {p:"chat",  o:["chat","chien"],  a:0, focus:"/a/ vs /jɛ̃/", ipa:"chat /ʃa/ · chien /ʃjɛ̃/"},
  {p:"son",   o:["son","sang"],    a:0, focus:"/ɔ̃/ vs /ɑ̃/",  ipa:"son /sɔ̃/ · sang /sɑ̃/"},
  {p:"tout",  o:["tout","tu"],     a:0, focus:"/u/ vs /y/",   ipa:"tout /tu/ · tu /ty/"},
  {p:"roue",  o:["roue","rue"],    a:0, focus:"/u/ vs /y/",   ipa:"roue /ʁu/ · rue /ʁy/"},
  {p:"nous",  o:["nous","nu"],     a:0, focus:"/u/ vs /y/",   ipa:"nous /nu/ · nu /ny/"},
  {p:"vous",  o:["vous","vu"],     a:0, focus:"/u/ vs /y/",   ipa:"vous /vu/ · vu /vy/"},
  {p:"vie",   o:["vie","vue"],     a:0, focus:"/i/ vs /y/",   ipa:"vie /vi/ · vue /vy/"},
  {p:"si",    o:["si","su"],       a:0, focus:"/i/ vs /y/",   ipa:"si /si/ · su /sy/"},
  {p:"lit",   o:["lit","lu"],      a:0, focus:"/i/ vs /y/",   ipa:"lit /li/ · lu /ly/"},
  {p:"beau",  o:["beau","bon"],    a:0, focus:"/o/ vs /ɔ̃/",   ipa:"beau /bo/ · bon /bɔ̃/"},
  {p:"mot",   o:["mot","mon"],     a:0, focus:"/o/ vs /ɔ̃/",   ipa:"mot /mo/ · mon /mɔ̃/"},
  {p:"dos",   o:["dos","don"],     a:0, focus:"/o/ vs /ɔ̃/",   ipa:"dos /do/ · don /dɔ̃/"},
  {p:"seau",  o:["seau","son"],    a:0, focus:"/o/ vs /ɔ̃/",   ipa:"seau /so/ · son /sɔ̃/"},
  {p:"faux",  o:["faux","fond"],   a:0, focus:"/o/ vs /ɔ̃/",   ipa:"faux /fo/ · fond /fɔ̃/"},
  {p:"pain",  o:["pain","pont"],   a:0, focus:"/ɛ̃/ vs /ɔ̃/",   ipa:"pain /pɛ̃/ · pont /pɔ̃/"},
  {p:"bain",  o:["bain","bon"],    a:0, focus:"/ɛ̃/ vs /ɔ̃/",   ipa:"bain /bɛ̃/ · bon /bɔ̃/"},
  {p:"fin",   o:["fin","font"],    a:0, focus:"/ɛ̃/ vs /ɔ̃/",   ipa:"fin /fɛ̃/ · font /fɔ̃/"},
  {p:"vin",   o:["vin","vent"],    a:0, focus:"/ɛ̃/ vs /ɑ̃/",   ipa:"vin /vɛ̃/ · vent /vɑ̃/"},
  {p:"main",  o:["main","ment"],   a:0, focus:"/ɛ̃/ vs /ɑ̃/",   ipa:"main /mɛ̃/ · ment /mɑ̃/"},
  {p:"rond",  o:["rond","rang"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"rond /ʁɔ̃/ · rang /ʁɑ̃/"},
  {p:"bon",   o:["bon","banc"],    a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"bon /bɔ̃/ · banc /bɑ̃/"},
  {p:"long",  o:["long","lent"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"long /lɔ̃/ · lent /lɑ̃/"},
  {p:"blond", o:["blond","blanc"], a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"blond /blɔ̃/ · blanc /blɑ̃/"},
  {p:"ton",   o:["ton","temps"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"ton /tɔ̃/ · temps /tɑ̃/"},
  {p:"sa",    o:["sa","sans"],     a:0, focus:"/a/ vs /ɑ̃/",   ipa:"sa /sa/ · sans /sɑ̃/"},
  {p:"ça",    o:["ça","cent"],     a:0, focus:"/a/ vs /ɑ̃/",   ipa:"ça /sa/ · cent /sɑ̃/"},
  {p:"va",    o:["va","vent"],     a:0, focus:"/a/ vs /ɑ̃/",   ipa:"va /va/ · vent /vɑ̃/"},
  {p:"peur",  o:["peur","peu"],    a:0, focus:"/œ/ vs /ø/",   ipa:"peur /pœʁ/ · peu /pø/"},
  {p:"sœur",  o:["sœur","ceux"],   a:0, focus:"/œ/ vs /ø/",   ipa:"sœur /sœʁ/ · ceux /sø/"},
  {p:"jeune", o:["jeune","jeu"],   a:0, focus:"/œ/ vs /ø/",   ipa:"jeune /ʒœn/ · jeu /ʒø/"},
  // simple oral-vowel pairs (chat/chaud family)
  {p:"chat",  o:["chat","chaud"],  a:0, focus:"/a/ vs /o/",   ipa:"chat /ʃa/ · chaud /ʃo/"},
  {p:"bas",   o:["bas","beau"],    a:0, focus:"/a/ vs /o/",   ipa:"bas /ba/ · beau /bo/"},
  {p:"ma",    o:["ma","mot"],      a:0, focus:"/a/ vs /o/",   ipa:"ma /ma/ · mot /mo/"},
  {p:"ta",    o:["ta","tôt"],      a:0, focus:"/a/ vs /o/",   ipa:"ta /ta/ · tôt /to/"},
  {p:"pas",   o:["pas","peau"],    a:0, focus:"/a/ vs /o/",   ipa:"pas /pa/ · peau /po/"},
  {p:"gras",  o:["gras","gros"],   a:0, focus:"/a/ vs /o/",   ipa:"gras /ɡʁa/ · gros /ɡʁo/"},
  {p:"tout",  o:["tout","tôt"],    a:0, focus:"/u/ vs /o/",   ipa:"tout /tu/ · tôt /to/"},
  {p:"sous",  o:["sous","seau"],   a:0, focus:"/u/ vs /o/",   ipa:"sous /su/ · seau /so/"},
  {p:"loup",  o:["loup","lu"],     a:0, focus:"/u/ vs /y/",   ipa:"loup /lu/ · lu /ly/"},
  {p:"joue",  o:["joue","jus"],    a:0, focus:"/u/ vs /y/",   ipa:"joue /ʒu/ · jus /ʒy/"},
  {p:"boue",  o:["boue","bu"],     a:0, focus:"/u/ vs /y/",   ipa:"boue /bu/ · bu /by/"},
  {p:"cou",   o:["cou","queue"],   a:0, focus:"/u/ vs /ø/",   ipa:"cou /ku/ · queue /kø/"},
  {p:"lit",   o:["lit","les"],     a:0, focus:"/i/ vs /e/",   ipa:"lit /li/ · les /le/"},
  {p:"ni",    o:["ni","nez"],      a:0, focus:"/i/ vs /e/",   ipa:"ni /ni/ · nez /ne/"},
  {p:"dit",   o:["dit","des"],     a:0, focus:"/i/ vs /e/",   ipa:"dit /di/ · des /de/"},
  {p:"mes",   o:["mes","mais"],    a:0, focus:"/e/ vs /ɛ/",   ipa:"mes /me/ · mais /mɛ/"},
  {p:"les",   o:["les","lait"],    a:0, focus:"/e/ vs /ɛ/",   ipa:"les /le/ · lait /lɛ/"},
  {p:"peu",   o:["peu","peau"],    a:0, focus:"/ø/ vs /o/",   ipa:"peu /pø/ · peau /po/"},
  {p:"deux",  o:["deux","dos"],    a:0, focus:"/ø/ vs /o/",   ipa:"deux /dø/ · dos /do/"},
  {p:"feu",   o:["feu","faux"],    a:0, focus:"/ø/ vs /o/",   ipa:"feu /fø/ · faux /fo/"},

  // ===== open vs closed O — the contrast that makes "saute" ≠ "sotte"
  {p:"saute", o:["saute","sotte"], a:0, focus:"/o/ vs /ɔ/", ipa:"saute /sot/ · sotte /sɔt/"},
  {p:"paume", o:["paume","pomme"], a:0, focus:"/o/ vs /ɔ/", ipa:"paume /pom/ · pomme /pɔm/"},
  {p:"haute", o:["haute","hotte"], a:0, focus:"/o/ vs /ɔ/", ipa:"haute /ot/ · hotte /ɔt/"},
  {p:"côte",  o:["côte","cote"],   a:0, focus:"/o/ vs /ɔ/", ipa:"côte /kot/ · cote /kɔt/"},
  // ===== the schwa: the little vowel that separates "le" from "les"
  {p:"le",  o:["le","les"],   a:0, focus:"/ə/ vs /e/", ipa:"le /lə/ · les /le/"},
  {p:"ce",  o:["ce","ces"],   a:0, focus:"/ə/ vs /e/", ipa:"ce /sə/ · ces /se/"},
  {p:"de",  o:["de","des"],   a:0, focus:"/ə/ vs /e/", ipa:"de /də/ · des /de/"},
  {p:"que", o:["que","quai"], a:0, focus:"/ə/ vs /e/", ipa:"que /kə/ · quai /ke/"},
  {p:"je",  o:["je","jeu"],   a:0, focus:"/ə/ vs /ø/", ipa:"je /ʒə/ · jeu /ʒø/"},
  {p:"ce",  o:["ce","ceux"],  a:0, focus:"/ə/ vs /ø/", ipa:"ce /sə/ · ceux /sø/"},
  {p:"de",  o:["de","deux"],  a:0, focus:"/ə/ vs /ø/", ipa:"de /də/ · deux /dø/"},
  // ===== oral vs nasal: /ɛ/ vs /ɛ̃/
  {p:"paix", o:["paix","pain"], a:0, focus:"/ɛ/ vs /ɛ̃/", ipa:"paix /pɛ/ · pain /pɛ̃/"},
  {p:"lait", o:["lait","lin"],  a:0, focus:"/ɛ/ vs /ɛ̃/", ipa:"lait /lɛ/ · lin /lɛ̃/"},
  {p:"mets", o:["mets","main"], a:0, focus:"/ɛ/ vs /ɛ̃/", ipa:"mets /mɛ/ · main /mɛ̃/"},
  {p:"fait", o:["fait","faim"], a:0, focus:"/ɛ/ vs /ɛ̃/", ipa:"fait /fɛ/ · faim /fɛ̃/"},
  {p:"sait", o:["sait","sain"], a:0, focus:"/ɛ/ vs /ɛ̃/", ipa:"sait /sɛ/ · sain /sɛ̃/"},
  // ===== /wa/ vs /wɛ̃/ — "loi" against "loin"
  {p:"moi",   o:["moi","moins"],   a:0, focus:"/wa/ vs /wɛ̃/", ipa:"moi /mwa/ · moins /mwɛ̃/"},
  {p:"soi",   o:["soi","soin"],    a:0, focus:"/wa/ vs /wɛ̃/", ipa:"soi /swa/ · soin /swɛ̃/"},
  {p:"loi",   o:["loi","loin"],    a:0, focus:"/wa/ vs /wɛ̃/", ipa:"loi /lwa/ · loin /lwɛ̃/"},
  {p:"foi",   o:["foi","foin"],    a:0, focus:"/wa/ vs /wɛ̃/", ipa:"foi /fwa/ · foin /fwɛ̃/"},
  {p:"poids", o:["poids","point"], a:0, focus:"/wa/ vs /wɛ̃/", ipa:"poids /pwa/ · point /pwɛ̃/"},
  // ===== consonants — voicing pairs
  {p:"pain",  o:["pain","bain"],   a:0, focus:"/p/ vs /b/", ipa:"pain /pɛ̃/ · bain /bɛ̃/"},
  {p:"poire", o:["poire","boire"], a:0, focus:"/p/ vs /b/", ipa:"poire /pwaʁ/ · boire /bwaʁ/"},
  {p:"peau",  o:["peau","beau"],   a:0, focus:"/p/ vs /b/", ipa:"peau /po/ · beau /bo/"},
  {p:"pas",   o:["pas","bas"],     a:0, focus:"/p/ vs /b/", ipa:"pas /pa/ · bas /ba/"},
  {p:"pu",    o:["pu","bu"],       a:0, focus:"/p/ vs /b/", ipa:"pu /py/ · bu /by/"},
  {p:"tout",  o:["tout","doux"],   a:0, focus:"/t/ vs /d/", ipa:"tout /tu/ · doux /du/"},
  {p:"temps", o:["temps","dent"],  a:0, focus:"/t/ vs /d/", ipa:"temps /tɑ̃/ · dent /dɑ̃/"},
  {p:"ton",   o:["ton","don"],     a:0, focus:"/t/ vs /d/", ipa:"ton /tɔ̃/ · don /dɔ̃/"},
  {p:"toit",  o:["toit","doigt"],  a:0, focus:"/t/ vs /d/", ipa:"toit /twa/ · doigt /dwa/"},
  {p:"tes",   o:["tes","des"],     a:0, focus:"/t/ vs /d/", ipa:"tes /te/ · des /de/"},
  {p:"car",   o:["car","gare"],    a:0, focus:"/k/ vs /g/", ipa:"car /kaʁ/ · gare /ɡaʁ/"},
  {p:"quand", o:["quand","gant"],  a:0, focus:"/k/ vs /g/", ipa:"quand /kɑ̃/ · gant /ɡɑ̃/"},
  {p:"cou",   o:["cou","goût"],    a:0, focus:"/k/ vs /g/", ipa:"cou /ku/ · goût /ɡu/"},
  {p:"quai",  o:["quai","gai"],    a:0, focus:"/k/ vs /g/", ipa:"quai /ke/ · gai /ɡe/"},
  {p:"fou",   o:["fou","vous"],    a:0, focus:"/f/ vs /v/", ipa:"fou /fu/ · vous /vu/"},
  {p:"faire", o:["faire","verre"], a:0, focus:"/f/ vs /v/", ipa:"faire /fɛʁ/ · verre /vɛʁ/"},
  {p:"fin",   o:["fin","vin"],     a:0, focus:"/f/ vs /v/", ipa:"fin /fɛ̃/ · vin /vɛ̃/"},
  {p:"font",  o:["font","vont"],   a:0, focus:"/f/ vs /v/", ipa:"font /fɔ̃/ · vont /vɔ̃/"},
  {p:"feu",   o:["feu","veut"],    a:0, focus:"/f/ vs /v/", ipa:"feu /fø/ · veut /vø/"},
  // ===== consonants — the sibilants
  {p:"chou",   o:["chou","joue"],     a:0, focus:"/ʃ/ vs /ʒ/", ipa:"chou /ʃu/ · joue /ʒu/"},
  {p:"cache",  o:["cache","cage"],    a:0, focus:"/ʃ/ vs /ʒ/", ipa:"cache /kaʃ/ · cage /kaʒ/"},
  {p:"bouche", o:["bouche","bouge"],  a:0, focus:"/ʃ/ vs /ʒ/", ipa:"bouche /buʃ/ · bouge /buʒ/"},
  {p:"chant",  o:["chant","gens"],    a:0, focus:"/ʃ/ vs /ʒ/", ipa:"chant /ʃɑ̃/ · gens /ʒɑ̃/"},
  {p:"sous",   o:["sous","chou"],     a:0, focus:"/s/ vs /ʃ/", ipa:"sous /su/ · chou /ʃu/"},
  {p:"sien",   o:["sien","chien"],    a:0, focus:"/s/ vs /ʃ/", ipa:"sien /sjɛ̃/ · chien /ʃjɛ̃/"},
  {p:"casse",  o:["casse","cache"],   a:0, focus:"/s/ vs /ʃ/", ipa:"casse /kas/ · cache /kaʃ/"},
  {p:"sale",   o:["sale","châle"],    a:0, focus:"/s/ vs /ʃ/", ipa:"sale /sal/ · châle /ʃal/"},
  {p:"sec",    o:["sec","chèque"],    a:0, focus:"/s/ vs /ʃ/", ipa:"sec /sɛk/ · chèque /ʃɛk/"},
  // ===== consonants — nasals, and the French R against L
  {p:"mou",  o:["mou","nous"],  a:0, focus:"/m/ vs /n/", ipa:"mou /mu/ · nous /nu/"},
  {p:"mon",  o:["mon","non"],   a:0, focus:"/m/ vs /n/", ipa:"mon /mɔ̃/ · non /nɔ̃/"},
  {p:"main", o:["main","nain"], a:0, focus:"/m/ vs /n/", ipa:"main /mɛ̃/ · nain /nɛ̃/"},
  {p:"mes",  o:["mes","nez"],   a:0, focus:"/m/ vs /n/", ipa:"mes /me/ · nez /ne/"},
  {p:"mot",  o:["mot","nos"],   a:0, focus:"/m/ vs /n/", ipa:"mot /mo/ · nos /no/"},
  {p:"roue", o:["roue","loup"], a:0, focus:"/ʁ/ vs /l/", ipa:"roue /ʁu/ · loup /lu/"},
  {p:"rire", o:["rire","lire"], a:0, focus:"/ʁ/ vs /l/", ipa:"rire /ʁiʁ/ · lire /liʁ/"},
  {p:"rond", o:["rond","long"], a:0, focus:"/ʁ/ vs /l/", ipa:"rond /ʁɔ̃/ · long /lɔ̃/"},
  {p:"rue",  o:["rue","lu"],    a:0, focus:"/ʁ/ vs /l/", ipa:"rue /ʁy/ · lu /ly/"},
  {p:"rat",  o:["rat","la"],    a:0, focus:"/ʁ/ vs /l/", ipa:"rat /ʁa/ · la /la/"},
];

// Level 2 — longer (multi-syllable) words, same clear contrasts.
const LEVEL2 = [
  {p:"bateau",  o:["bateau","bâton"],     a:0, focus:"/o/ vs /ɔ̃/",  ipa:"bateau /bato/ · bâton /batɔ̃/"},
  {p:"manteau", o:["manteau","menton"],   a:0, focus:"/o/ vs /ɔ̃/",  ipa:"manteau /mɑ̃to/ · menton /mɑ̃tɔ̃/"},
  {p:"chapeau", o:["chapeau","chapon"],   a:0, focus:"/o/ vs /ɔ̃/",  ipa:"chapeau /ʃapo/ · chapon /ʃapɔ̃/"},
  {p:"oiseau",  o:["oiseau","oison"],     a:0, focus:"/o/ vs /ɔ̃/",  ipa:"oiseau /wazo/ · oison /wazɔ̃/"},
  {p:"drapeau", o:["drapeau","drapons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"drapeau /dʁapo/ · drapons /dʁapɔ̃/"},
  {p:"couteau", o:["couteau","coûtons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"couteau /kuto/ · coûtons /kutɔ̃/"},
  {p:"rideau",  o:["rideau","ridons"],    a:0, focus:"/o/ vs /ɔ̃/",  ipa:"rideau /ʁido/ · ridons /ʁidɔ̃/"},
  {p:"cerveau", o:["cerveau","servons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"cerveau /sɛʁvo/ · servons /sɛʁvɔ̃/"},
  {p:"noyau",   o:["noyau","noyons"],     a:0, focus:"/o/ vs /ɔ̃/",  ipa:"noyau /nwajo/ · noyons /nwajɔ̃/"},
  {p:"berceau", o:["berceau","berçons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"berceau /bɛʁso/ · berçons /bɛʁsɔ̃/"},
  {p:"marron",  o:["marron","marrant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"marron /maʁɔ̃/ · marrant /maʁɑ̃/"},
  {p:"savon",   o:["savon","savant"],     a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"savon /savɔ̃/ · savant /savɑ̃/"},
  {p:"menton",  o:["menton","mentant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"menton /mɑ̃tɔ̃/ · mentant /mɑ̃tɑ̃/"},
  {p:"ballon",  o:["ballon","ballant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"ballon /balɔ̃/ · ballant /balɑ̃/"},
  {p:"bouchon", o:["bouchon","bouchant"], a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"bouchon /buʃɔ̃/ · bouchant /buʃɑ̃/"},
  {p:"glaçon",  o:["glaçon","glaçant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"glaçon /ɡlasɔ̃/ · glaçant /ɡlasɑ̃/"},
  {p:"maçon",   o:["maçon","massant"],    a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"maçon /masɔ̃/ · massant /masɑ̃/"},
  {p:"cochon",  o:["cochon","cachant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"cochon /kɔʃɔ̃/ · cachant /kaʃɑ̃/"},
  {p:"torchon", o:["torchon","torchant"], a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"torchon /tɔʁʃɔ̃/ · torchant /tɔʁʃɑ̃/"},
  {p:"blouson", o:["blouson","blousant"], a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"blouson /bluzɔ̃/ · blousant /bluzɑ̃/"},
  {p:"flocon",  o:["flocon","floquant"],  a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"flocon /flɔkɔ̃/ · floquant /flɔkɑ̃/"},
  {p:"melon",   o:["melon","mêlant"],     a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"melon /məlɔ̃/ · mêlant /mɛlɑ̃/"},
  {p:"jeton",   o:["jeton","jetant"],     a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"jeton /ʒətɔ̃/ · jetant /ʒətɑ̃/"},
  {p:"raisin",  o:["raisin","raison"],    a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"raisin /ʁɛzɛ̃/ · raison /ʁɛzɔ̃/"},
  {p:"lapin",   o:["lapin","lapon"],      a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"lapin /lapɛ̃/ · lapon /lapɔ̃/"},
  {p:"bassin",  o:["bassin","basson"],    a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"bassin /basɛ̃/ · basson /basɔ̃/"},
  {p:"moulin",  o:["moulin","moulons"],   a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"moulin /mulɛ̃/ · moulons /mulɔ̃/"},
  {p:"ami",     o:["ami","amant"],        a:0, focus:"/i/ vs /ɑ̃/",  ipa:"ami /ami/ · amant /amɑ̃/"},
  {p:"dessus",  o:["dessus","dessous"],   a:0, focus:"/y/ vs /u/",  ipa:"dessus /dəsy/ · dessous /dəsu/"},
  {p:"ici",     o:["ici","issu"],         a:0, focus:"/i/ vs /y/",  ipa:"ici /isi/ · issu /isy/"},
  // voicing /s/ vs /z/ and other simple multi-syllable contrasts
  {p:"coussin", o:["coussin","cousin"],   a:0, focus:"/s/ vs /z/",  ipa:"coussin /kusɛ̃/ · cousin /kuzɛ̃/"},
  {p:"poisson", o:["poisson","poison"],   a:0, focus:"/s/ vs /z/",  ipa:"poisson /pwasɔ̃/ · poison /pwazɔ̃/"},
  {p:"dessert", o:["dessert","désert"],   a:0, focus:"/s/ vs /z/",  ipa:"dessert /desɛʁ/ · désert /dezɛʁ/"},
  {p:"cheveux", o:["cheveux","chevaux"],  a:0, focus:"/ø/ vs /o/",  ipa:"cheveux /ʃəvø/ · chevaux /ʃəvo/"},
  {p:"château", o:["château","chatons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"château /ʃato/ · chatons /ʃatɔ̃/"},
  {p:"été",     o:["été","était"],        a:0, focus:"/e/ vs /ɛ/",  ipa:"été /ete/ · était /etɛ/"},

  {p:"poisson", o:["poisson","boisson"], a:0, focus:"/p/ vs /b/", ipa:"poisson /pwasɔ̃/ · boisson /bwasɔ̃/"},
  {p:"carré",   o:["carré","garé"],      a:0, focus:"/k/ vs /g/", ipa:"carré /kaʁe/ · garé /ɡaʁe/"},
  {p:"bouchon", o:["bouchon","bougeons"],a:0, focus:"/ʃ/ vs /ʒ/", ipa:"bouchon /buʃɔ̃/ · bougeons /buʒɔ̃/"},
  {p:"casser",  o:["casser","cacher"],   a:0, focus:"/s/ vs /ʃ/", ipa:"casser /kase/ · cacher /kaʃe/"},
  {p:"arrêt",   o:["arrêt","allait"],    a:0, focus:"/ʁ/ vs /l/", ipa:"arrêt /aʁɛ/ · allait /alɛ/"},
  {p:"côté",    o:["côté","coté"],       a:0, focus:"/o/ vs /ɔ/", ipa:"côté /kote/ · coté /kɔte/"},
];

// Level 3 — the same sounds inside full sentences.
const LEVEL3 = [
  {p:"J'ai promené mon chat.",        o:["J'ai promené mon chat.","J'ai promené mon chien."],         a:0, focus:"/a/ vs /jɛ̃/", ipa:"chat /ʃa/ · chien /ʃjɛ̃/"},
  {p:"Il a marqué le but.",           o:["Il a marqué le but.","Il a marqué le bout."],               a:0, focus:"/y/ vs /u/",  ipa:"but /by/ · bout /bu/"},
  {p:"La roue tourne lentement.",     o:["La roue tourne lentement.","La rue tourne lentement."],     a:0, focus:"/u/ vs /y/",  ipa:"roue /ʁu/ · rue /ʁy/"},
  {p:"J'adore cette vue.",            o:["J'adore cette vue.","J'adore cette vie."],                  a:0, focus:"/y/ vs /i/",  ipa:"vue /vy/ · vie /vi/"},
  {p:"Le chat dort dessus.",          o:["Le chat dort dessus.","Le chat dort dessous."],            a:0, focus:"/y/ vs /u/",  ipa:"dessus /dəsy/ · dessous /dəsu/"},
  {p:"Il vend des pulls.",            o:["Il vend des pulls.","Il vend des poules."],                 a:0, focus:"/y/ vs /u/",  ipa:"pull /pyl/ · poule /pul/"},
  {p:"Il a très peu.",                o:["Il a très peu.","Il a très peur."],                         a:0, focus:"/ø/ vs /œ/",  ipa:"peu /pø/ · peur /pœʁ/"},
  {p:"Le bateau est grand.",          o:["Le bateau est grand.","Le bâton est grand."],               a:0, focus:"/o/ vs /ɔ̃/",  ipa:"bateau /bato/ · bâton /batɔ̃/"},
  {p:"Il porte un manteau marron.",   o:["Il porte un manteau marron.","Il porte un manteau marrant."], a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"marron /maʁɔ̃/ · marrant /maʁɑ̃/"},
  {p:"C'est un bon savon.",           o:["C'est un bon savon.","C'est un bon savant."],               a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"savon /savɔ̃/ · savant /savɑ̃/"},
  {p:"Le train est là.",              o:["Le train est là.","Le train est lent."],                   a:0, focus:"/a/ vs /ɑ̃/",  ipa:"là /la/ · lent /lɑ̃/"},
  {p:"Il passe à toi.",               o:["Il passe à toi.","Il pense à toi."],                        a:0, focus:"/a/ vs /ɑ̃/",  ipa:"passe /pas/ · pense /pɑ̃s/"},
  {p:"Il fait du vin.",               o:["Il fait du vin.","Il fait du vent."],                       a:0, focus:"/ɛ̃/ vs /ɑ̃/", ipa:"vin /vɛ̃/ · vent /vɑ̃/"},
  {p:"Il peint le mur.",              o:["Il peint le mur.","Il pend le mur."],                       a:0, focus:"/ɛ̃/ vs /ɑ̃/", ipa:"peint /pɛ̃/ · pend /pɑ̃/"},
  {p:"C'est un beau gâteau.",         o:["C'est un beau gâteau.","C'est un bon gâteau."],             a:0, focus:"/o/ vs /ɔ̃/",  ipa:"beau /bo/ · bon /bɔ̃/"},
  {p:"C'est mon seau.",               o:["C'est mon seau.","C'est mon son."],                         a:0, focus:"/o/ vs /ɔ̃/",  ipa:"seau /so/ · son /sɔ̃/"},
  {p:"Il a les cheveux blancs.",      o:["Il a les cheveux blancs.","Il a les cheveux blonds."],      a:0, focus:"/ɑ̃/ vs /ɔ̃/", ipa:"blanc /blɑ̃/ · blond /blɔ̃/"},
  {p:"Dessine un rond.",              o:["Dessine un rond.","Dessine un rang."],                      a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"rond /ʁɔ̃/ · rang /ʁɑ̃/"},
  {p:"Le film est long.",             o:["Le film est long.","Le film est lent."],                   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"long /lɔ̃/ · lent /lɑ̃/"},
  {p:"Le chien ronge l'os.",          o:["Le chien ronge l'os.","Le chien range l'os."],              a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"ronge /ʁɔ̃ʒ/ · range /ʁɑ̃ʒ/"},
  {p:"C'est une forte pente.",        o:["C'est une forte pente.","C'est une forte ponte."],          a:0, focus:"/ɑ̃/ vs /ɔ̃/", ipa:"pente /pɑ̃t/ · ponte /pɔ̃t/"},
  {p:"Quel beau teint !",             o:["Quel beau teint !","Quel beau ton !"],                      a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"teint /tɛ̃/ · ton /tɔ̃/"},
  {p:"Je vois le train.",             o:["Je vois le train.","Je vois le tronc."],                    a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"train /tʁɛ̃/ · tronc /tʁɔ̃/"},
  {p:"C'est un grand pin.",           o:["C'est un grand pin.","C'est un grand pont."],               a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"pin /pɛ̃/ · pont /pɔ̃/"},
  {p:"J'aime le raisin.",             o:["J'aime le raisin.","J'aime la raison."],                    a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"raisin /ʁɛzɛ̃/ · raison /ʁɛzɔ̃/"},
  {p:"Le pont est solide.",           o:["Le pont est solide.","Le pan est solide."],                 a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"pont /pɔ̃/ · pan /pɑ̃/"},
  {p:"Quel beau banc !",              o:["Quel beau banc !","Quel beau bond !"],                      a:0, focus:"/ɑ̃/ vs /ɔ̃/", ipa:"banc /bɑ̃/ · bond /bɔ̃/"},
  {p:"C'est une jolie rue.",          o:["C'est une jolie rue.","C'est une jolie roue."],             a:0, focus:"/y/ vs /u/",  ipa:"rue /ʁy/ · roue /ʁu/"},
  {p:"Quel bon vin !",                o:["Quel bon vin !","Quel bon vent !"],                         a:0, focus:"/ɛ̃/ vs /ɑ̃/", ipa:"vin /vɛ̃/ · vent /vɑ̃/"},
  {p:"Quel joli chapeau !",           o:["Quel joli chapeau !","Quel joli chapon !"],                 a:0, focus:"/o/ vs /ɔ̃/",  ipa:"chapeau /ʃapo/ · chapon /ʃapɔ̃/"},
  {p:"J'ai mangé du poisson.",        o:["J'ai mangé du poisson.","J'ai mangé du poison."],           a:0, focus:"/s/ vs /z/",  ipa:"poisson /pwasɔ̃/ · poison /pwazɔ̃/"},
  {p:"C'est mon cousin.",             o:["C'est mon cousin.","C'est mon coussin."],                   a:0, focus:"/z/ vs /s/",  ipa:"cousin /kuzɛ̃/ · coussin /kusɛ̃/"},
  {p:"Elle a de beaux cheveux.",      o:["Elle a de beaux cheveux.","Elle a de beaux chevaux."],      a:0, focus:"/ø/ vs /o/",  ipa:"cheveux /ʃəvø/ · chevaux /ʃəvo/"},
  {p:"Le dessert est bon.",           o:["Le dessert est bon.","Le désert est bon."],                 a:0, focus:"/s/ vs /z/",  ipa:"dessert /desɛʁ/ · désert /dezɛʁ/"},
  {p:"C'est trop gras.",              o:["C'est trop gras.","C'est trop gros."],                      a:0, focus:"/a/ vs /o/",  ipa:"gras /ɡʁa/ · gros /ɡʁo/"},

  {p:"La côte est longue.",        o:["La côte est longue.","La cote est longue."],             a:0, focus:"/o/ vs /ɔ/",    ipa:"côte /kot/ · cote /kɔt/"},
  {p:"C'est une belle pomme.",     o:["C'est une belle pomme.","C'est une belle paume."],       a:0, focus:"/o/ vs /ɔ/",    ipa:"pomme /pɔm/ · paume /pom/"},
  {p:"Je prends le train.",        o:["Je prends le train.","Je prends les trains."],           a:0, focus:"/ə/ vs /e/",    ipa:"le /lə/ · les /le/"},
  {p:"Il veut ce livre.",          o:["Il veut ce livre.","Il veut ces livres."],               a:0, focus:"/ə/ vs /e/",    ipa:"ce /sə/ · ces /se/"},
  {p:"C'est ce qu'il veut.",       o:["C'est ce qu'il veut.","C'est ceux qu'il veut."],         a:0, focus:"/ə/ vs /ø/",    ipa:"ce /sə/ · ceux /sø/"},
  {p:"Il achète du lait.",         o:["Il achète du lait.","Il achète du lin."],                a:0, focus:"/ɛ/ vs /ɛ̃/",   ipa:"lait /lɛ/ · lin /lɛ̃/"},
  {p:"Le point est important.",    o:["Le point est important.","Le poids est important."],     a:0, focus:"/wa/ vs /wɛ̃/",  ipa:"point /pwɛ̃/ · poids /pwa/"},
  {p:"Il prend un bain.",          o:["Il prend un bain.","Il prend un pain."],                 a:0, focus:"/p/ vs /b/",    ipa:"bain /bɛ̃/ · pain /pɛ̃/"},
  {p:"Ce pas est long.",           o:["Ce pas est long.","Ce bas est long."],                   a:0, focus:"/p/ vs /b/",    ipa:"pas /pa/ · bas /ba/"},
  {p:"Regarde le toit.",           o:["Regarde le toit.","Regarde le doigt."],                  a:0, focus:"/t/ vs /d/",    ipa:"toit /twa/ · doigt /dwa/"},
  {p:"C'est un grand don.",        o:["C'est un grand don.","C'est un grand ton."],             a:0, focus:"/t/ vs /d/",    ipa:"don /dɔ̃/ · ton /tɔ̃/"},
  {p:"Il aime ce goût.",           o:["Il aime ce goût.","Il aime ce cou."],                    a:0, focus:"/k/ vs /g/",    ipa:"goût /ɡu/ · cou /ku/"},
  {p:"Il vend le bois.",           o:["Il vend le bois.","Il fend le bois."],                   a:0, focus:"/f/ vs /v/",    ipa:"vend /vɑ̃/ · fend /fɑ̃/"},
  {p:"Ferme la cage.",             o:["Ferme la cage.","Ferme la cache."],                      a:0, focus:"/ʃ/ vs /ʒ/",    ipa:"cage /kaʒ/ · cache /kaʃ/"},
  {p:"C'est le chien.",            o:["C'est le chien.","C'est le sien."],                      a:0, focus:"/s/ vs /ʃ/",    ipa:"chien /ʃjɛ̃/ · sien /sjɛ̃/"},
  {p:"Il casse la porte.",         o:["Il casse la porte.","Il cache la porte."],               a:0, focus:"/s/ vs /ʃ/",    ipa:"casse /kas/ · cache /kaʃ/"},
  {p:"Il aime lire.",              o:["Il aime lire.","Il aime rire."],                         a:0, focus:"/ʁ/ vs /l/",    ipa:"lire /liʁ/ · rire /ʁiʁ/"},
  {p:"C'est nous.",                o:["C'est nous.","C'est mou."],                              a:0, focus:"/m/ vs /n/",    ipa:"nous /nu/ · mou /mu/"},
  {p:"Les faits sont là.",         o:["Les faits sont là.","Les fées sont là."],                a:0, focus:"/e/ vs /ɛ/",    ipa:"fait /fɛ/ · fée /fe/"},
];

/* ===== Italian translations (shown under each French word / sentence) ===== */
const TRANS = {
  // Level 1 — words
  "chat":"gatto","chien":"cane","son":"suono","sang":"sangue","tout":"tutto","tu":"tu",
  "roue":"ruota","rue":"strada","nous":"noi","nu":"nudo","vous":"voi","vu":"visto",
  "vie":"vita","vue":"vista","si":"se","su":"saputo","lit":"letto","lu":"letto (p.p.)",
  "beau":"bello","bon":"buono","mot":"parola","mon":"mio","dos":"schiena","don":"dono",
  "seau":"secchio","faux":"falso","fond":"fondo","pain":"pane","pont":"ponte","bain":"bagno",
  "fin":"fine","font":"fanno","vin":"vino","vent":"vento","main":"mano","ment":"mente",
  "rond":"tondo","rang":"fila","banc":"panca","long":"lungo","lent":"lento","blond":"biondo",
  "blanc":"bianco","ton":"tono","temps":"tempo","sa":"sua","sans":"senza","ça":"questo",
  "cent":"cento","va":"va","peur":"paura","peu":"poco","sœur":"sorella","ceux":"quelli",
  "jeune":"giovane","jeu":"gioco",
  // Level 1 — new simple pairs
  "chaud":"caldo","bas":"basso","ma":"mia","ta":"tua","tôt":"presto","pas":"passo",
  "peau":"pelle","gras":"grasso","gros":"grosso","sous":"sotto","loup":"lupo","joue":"guancia",
  "jus":"succo","boue":"fango","bu":"bevuto","cou":"collo","queue":"coda","les":"i / gli",
  "ni":"né","nez":"naso","dit":"detto","des":"dei / degli","mes":"miei","mais":"ma",
  "lait":"latte","deux":"due","feu":"fuoco",
  // Level 2 — longer words
  "bateau":"barca","bâton":"bastone","manteau":"cappotto","menton":"mento","chapeau":"cappello",
  "chapon":"cappone","oiseau":"uccello","oison":"papero","drapeau":"bandiera","drapons":"(noi) drappeggiamo",
  "couteau":"coltello","coûtons":"(noi) costiamo","rideau":"tenda","ridons":"(noi) ridiamo",
  "cerveau":"cervello","servons":"(noi) serviamo","noyau":"nocciolo","noyons":"(noi) anneghiamo",
  "berceau":"culla","berçons":"(noi) culliamo","marron":"marrone","marrant":"divertente",
  "savon":"sapone","savant":"sapiente","mentant":"(che) mente","ballon":"pallone","ballant":"penzolante",
  "bouchon":"tappo","bouchant":"(che) tappa","glaçon":"cubetto di ghiaccio","glaçant":"agghiacciante",
  "maçon":"muratore","massant":"(che) massaggia","cochon":"maiale","cachant":"(che) nasconde",
  "torchon":"straccio","torchant":"(che) pulisce","blouson":"giubbotto","blousant":"(che) si gonfia",
  "flocon":"fiocco","floquant":"(che) riveste","melon":"melone","mêlant":"(che) mescola",
  "jeton":"gettone","jetant":"(che) getta","raisin":"uva","raison":"ragione","lapin":"coniglio",
  "lapon":"lappone","bassin":"bacino","basson":"fagotto","moulin":"mulino","moulons":"(noi) maciniamo",
  "ami":"amico","amant":"amante","dessus":"sopra","dessous":"sotto","ici":"qui","issu":"derivato",
  "coussin":"cuscino","cousin":"cugino","poisson":"pesce","poison":"veleno","dessert":"dolce",
  "désert":"deserto","cheveux":"capelli","chevaux":"cavalli","château":"castello","chatons":"gattini",
  "été":"estate","était":"era",
  // ----- open/closed O, the schwa, and the new nasal contrasts
  "saute":"salta","sotte":"sciocca","paume":"palmo","pomme":"mela","haute":"alta","hotte":"gerla",
  "côte":"costa","cote":"quotazione","côté":"lato","coté":"quotato",
  "le":"il","ce":"questo","ces":"questi","de":"di","que":"che","quai":"banchina","je":"io",
  "paix":"pace","lin":"lino","mets":"piatto","fait":"fatto","faim":"fame","sait":"sa","sain":"sano","fée":"fata",
  "moi":"me","moins":"meno","soi":"sé","soin":"cura","loi":"legge","loin":"lontano",
  "foi":"fede","foin":"fieno","poids":"peso","point":"punto",
  // ----- consonants
  "poire":"pera","boire":"bere","pu":"potuto","boisson":"bevanda",
  "doux":"dolce","dent":"dente","toit":"tetto","doigt":"dito","tes":"tuoi",
  "car":"pullman","gare":"stazione","quand":"quando","gant":"guanto","goût":"gusto","gai":"allegro",
  "carré":"quadrato","garé":"parcheggiato",
  "fou":"pazzo","faire":"fare","verre":"bicchiere","vont":"vanno","veut":"vuole",
  "fend":"spacca","vend":"vende",
  "chou":"cavolo","cache":"nasconde","cage":"gabbia","bouche":"bocca","bouge":"si muove",
  "chant":"canto","gens":"gente","bougeons":"(noi) muoviamo",
  "sien":"suo","casse":"rompe","sale":"sporco","châle":"scialle","sec":"secco","chèque":"assegno",
  "casser":"rompere","cacher":"nascondere",
  "mou":"molle","non":"no","nain":"nano","nos":"nostri",
  "rire":"ridere","lire":"leggere","rat":"topo","la":"la","arrêt":"fermata","allait":"andava",
  // ----- the new sentences
  "La côte est longue.":"La costa è lunga.",
  "La cote est longue.":"La quotazione è lunga.",
  "C'est une belle pomme.":"È una bella mela.",
  "C'est une belle paume.":"È un bel palmo.",
  "Je prends le train.":"Prendo il treno.",
  "Je prends les trains.":"Prendo i treni.",
  "Il veut ce livre.":"Vuole questo libro.",
  "Il veut ces livres.":"Vuole questi libri.",
  "C'est ce qu'il veut.":"È quello che vuole.",
  "C'est ceux qu'il veut.":"Sono quelli che vuole.",
  "Il achète du lait.":"Compra del latte.",
  "Il achète du lin.":"Compra del lino.",
  "Le point est important.":"Il punto è importante.",
  "Le poids est important.":"Il peso è importante.",
  "Il prend un bain.":"Fa un bagno.",
  "Il prend un pain.":"Prende un pane.",
  "Ce pas est long.":"Questo passo è lungo.",
  "Ce bas est long.":"Questa calza è lunga.",
  "Regarde le toit.":"Guarda il tetto.",
  "Regarde le doigt.":"Guarda il dito.",
  "C'est un grand don.":"È un grande dono.",
  "C'est un grand ton.":"È un gran tono.",
  "Il aime ce goût.":"Gli piace questo gusto.",
  "Il aime ce cou.":"Gli piace questo collo.",
  "Il vend le bois.":"Vende il legno.",
  "Il fend le bois.":"Spacca il legno.",
  "Ferme la cage.":"Chiudi la gabbia.",
  "Ferme la cache.":"Chiudi il nascondiglio.",
  "C'est le chien.":"È il cane.",
  "C'est le sien.":"È il suo.",
  "Il casse la porte.":"Rompe la porta.",
  "Il cache la porte.":"Nasconde la porta.",
  "Il aime lire.":"Gli piace leggere.",
  "Il aime rire.":"Gli piace ridere.",
  "C'est nous.":"Siamo noi.",
  "C'est mou.":"È molle.",
  "Les faits sont là.":"I fatti sono lì.",
  "Les fées sont là.":"Le fate sono lì.",
  // Level 3 — sentences
  "J'ai promené mon chat.":"Ho portato a spasso il mio gatto.",
  "J'ai promené mon chien.":"Ho portato a spasso il mio cane.",
  "Il a marqué le but.":"Ha segnato il gol.",
  "Il a marqué le bout.":"Ha marcato l'estremità.",
  "La roue tourne lentement.":"La ruota gira lentamente.",
  "La rue tourne lentement.":"La strada gira lentamente.",
  "J'adore cette vue.":"Adoro questa vista.",
  "J'adore cette vie.":"Adoro questa vita.",
  "Le chat dort dessus.":"Il gatto dorme sopra.",
  "Le chat dort dessous.":"Il gatto dorme sotto.",
  "Il vend des pulls.":"Vende dei maglioni.",
  "Il vend des poules.":"Vende delle galline.",
  "Il a très peu.":"Ne ha molto poco.",
  "Il a très peur.":"Ha molta paura.",
  "Le bateau est grand.":"La barca è grande.",
  "Le bâton est grand.":"Il bastone è grande.",
  "Il porte un manteau marron.":"Indossa un cappotto marrone.",
  "Il porte un manteau marrant.":"Indossa un cappotto divertente.",
  "C'est un bon savon.":"È un buon sapone.",
  "C'est un bon savant.":"È un buon sapiente.",
  "Le train est là.":"Il treno è qui.",
  "Le train est lent.":"Il treno è lento.",
  "Il passe à toi.":"Tocca a te.",
  "Il pense à toi.":"Pensa a te.",
  "Il fait du vin.":"Fa il vino.",
  "Il fait du vent.":"Tira vento.",
  "Il peint le mur.":"Dipinge il muro.",
  "Il pend le mur.":"Appende il muro.",
  "C'est un beau gâteau.":"È una bella torta.",
  "C'est un bon gâteau.":"È una buona torta.",
  "C'est mon seau.":"È il mio secchio.",
  "C'est mon son.":"È il mio suono.",
  "Il a les cheveux blancs.":"Ha i capelli bianchi.",
  "Il a les cheveux blonds.":"Ha i capelli biondi.",
  "Dessine un rond.":"Disegna un cerchio.",
  "Dessine un rang.":"Disegna una fila.",
  "Le film est long.":"Il film è lungo.",
  "Le film est lent.":"Il film è lento.",
  "Le chien ronge l'os.":"Il cane rosicchia l'osso.",
  "Le chien range l'os.":"Il cane mette a posto l'osso.",
  "C'est une forte pente.":"È una forte pendenza.",
  "C'est une forte ponte.":"È una grande covata.",
  "Quel beau teint !":"Che bel colorito!",
  "Quel beau ton !":"Che bel tono!",
  "Je vois le train.":"Vedo il treno.",
  "Je vois le tronc.":"Vedo il tronco.",
  "C'est un grand pin.":"È un grande pino.",
  "C'est un grand pont.":"È un grande ponte.",
  "J'aime le raisin.":"Mi piace l'uva.",
  "J'aime la raison.":"Amo la ragione.",
  "Le pont est solide.":"Il ponte è solido.",
  "Le pan est solide.":"Il lembo è solido.",
  "Quel beau banc !":"Che bella panchina!",
  "Quel beau bond !":"Che bel balzo!",
  "C'est une jolie rue.":"È una bella strada.",
  "C'est une jolie roue.":"È una bella ruota.",
  "Quel bon vin !":"Che buon vino!",
  "Quel bon vent !":"Che buon vento!",
  "Quel joli chapeau !":"Che bel cappello!",
  "Quel joli chapon !":"Che bel cappone!",
  "J'ai mangé du poisson.":"Ho mangiato del pesce.",
  "J'ai mangé du poison.":"Ho mangiato del veleno.",
  "C'est mon cousin.":"È mio cugino.",
  "C'est mon coussin.":"È il mio cuscino.",
  "Elle a de beaux cheveux.":"Ha bei capelli.",
  "Elle a de beaux chevaux.":"Ha bei cavalli.",
  "Le dessert est bon.":"Il dolce è buono.",
  "Le désert est bon.":"Il deserto è buono.",
  "C'est trop gras.":"È troppo grasso.",
  "C'est trop gros.":"È troppo grosso.",
};

/* ===== "Odd" prompts =====
   Grammatically correct but not something you'd normally say — they exist only
   to give a clean minimal pair for the sound. After the user answers we flag
   these so they know the phrase isn't meant to make real-world sense. */
const ODD = new Set([
  // Level 2 — real "nous" verb forms, but you'd never say them on their own
  "drapons","coûtons","ridons","servons","noyons","berçons","moulons",
  // Level 3 — the semantically odd half of each sentence pair
  "Il a marqué le bout.","La rue tourne lentement.","Il porte un manteau marrant.",
  "Il pend le mur.","C'est mon son.","Le chien range l'os.","C'est une forte ponte.",
  "Le pan est solide.","Quel joli chapon !","J'ai mangé du poison.","Le désert est bon.",
  // Level 1/2 — real words, but you'd never say them alone
  "bougeons",
  // Level 3 — the semantically odd half of each new pair
  "La cote est longue.","C'est une belle paume.","Il aime ce cou.","Il cache la porte.",
  "C'est un grand ton.","Il veut ces livres.",
]);

/* ---- Level 5 — read aloud full sentences about French / European law ---- */
const LAW_SENTENCES = [
  {s:"Le Parlement européen adopte de nouvelles directives.",            it:"Il Parlamento europeo adotta nuove direttive."},
  {s:"La Cour de cassation a rendu son arrêt hier.",                     it:"La Corte di cassazione ha emesso la sentenza ieri."},
  {s:"Le Conseil constitutionnel vérifie la conformité des lois.",       it:"Il Consiglio costituzionale verifica la conformità delle leggi."},
  {s:"Chaque citoyen européen bénéficie de la libre circulation.",       it:"Ogni cittadino europeo beneficia della libera circolazione."},
  {s:"Le droit communautaire prime sur le droit national.",              it:"Il diritto comunitario prevale sul diritto nazionale."},
  {s:"La Commission européenne propose un nouveau règlement.",           it:"La Commissione europea propone un nuovo regolamento."},
  {s:"Les traités garantissent les droits fondamentaux des personnes.",  it:"I trattati garantiscono i diritti fondamentali delle persone."},
  {s:"Le tribunal administratif examine les recours des citoyens.",      it:"Il tribunale amministrativo esamina i ricorsi dei cittadini."},
  {s:"La Convention européenne protège les libertés individuelles.",     it:"La Convenzione europea protegge le libertà individuali."},
  {s:"Le législateur a voté le projet de loi à l'unanimité.",            it:"Il legislatore ha votato il disegno di legge all'unanimità."},
  {s:"La jurisprudence interprète les textes juridiques ambigus.",       it:"La giurisprudenza interpreta i testi giuridici ambigui."},
  {s:"Le Conseil d'État conseille le gouvernement sur les décrets.",     it:"Il Consiglio di Stato consiglia il governo sui decreti."},
  {s:"La Cour de justice de l'Union européenne siège à Luxembourg.",     it:"La Corte di giustizia dell'Unione europea ha sede a Lussemburgo."},
  {s:"Le règlement protège les données personnelles des utilisateurs.",  it:"Il regolamento protegge i dati personali degli utenti."},
  {s:"L'avocat plaide la cause de son client devant le juge.",           it:"L'avvocato difende la causa del suo cliente davanti al giudice."},
  {s:"Le contrat engage les deux parties signataires.",                  it:"Il contratto vincola le due parti firmatarie."},
  {s:"La séparation des pouvoirs garantit l'indépendance de la justice.", it:"La separazione dei poteri garantisce l'indipendenza della giustizia."},
  {s:"Les États membres ratifient le traité européen.",                  it:"Gli Stati membri ratificano il trattato europeo."},
  {s:"Le juge d'instruction ouvre une enquête préliminaire.",           it:"Il giudice istruttore apre un'indagine preliminare."},
  {s:"La loi entre en vigueur le premier janvier.",                     it:"La legge entra in vigore il primo gennaio."},
  {s:"Le procureur requiert une peine de prison.",                      it:"Il procuratore chiede una pena detentiva."},
  {s:"Les députés votent le budget de l'État.",                         it:"I deputati votano il bilancio dello Stato."},
  {s:"La directive doit être transposée en droit interne.",             it:"La direttiva deve essere recepita nel diritto interno."},
  {s:"Le prévenu bénéficie de la présomption d'innocence.",             it:"L'imputato beneficia della presunzione di innocenza."},
  {s:"La chambre criminelle statue sur le pourvoi.",                    it:"La camera penale si pronuncia sul ricorso."},
  {s:"Le règlement européen s'applique directement.",                   it:"Il regolamento europeo si applica direttamente."},
  {s:"L'accord commercial sera ratifié par les parlements.",            it:"L'accordo commerciale sarà ratificato dai parlamenti."},
  {s:"La victime peut se constituer partie civile.",                    it:"La vittima può costituirsi parte civile."},
  {s:"Le Sénat examine le texte en seconde lecture.",                   it:"Il Senato esamina il testo in seconda lettura."},
  {s:"La juridiction compétente rejette la demande.",                   it:"La giurisdizione competente respinge la domanda."},
  {s:"Les données personnelles doivent être traitées loyalement.",      it:"I dati personali devono essere trattati lealmente."},
  {s:"Le contribuable conteste le redressement fiscal.",                it:"Il contribuente contesta l'accertamento fiscale."},
  {s:"Le salarié saisit le conseil de prud'hommes.",                    it:"Il lavoratore adisce il tribunale del lavoro."},
  {s:"La cour d'appel infirme le jugement de première instance.",       it:"La corte d'appello riforma la sentenza di primo grado."},
  {s:"Le notaire authentifie l'acte de vente.",                         it:"Il notaio autentica l'atto di vendita."},
  {s:"L'ordonnance est publiée au Journal officiel.",                   it:"L'ordinanza è pubblicata nella Gazzetta ufficiale."},
  {s:"Le principe de proportionnalité limite l'action publique.",       it:"Il principio di proporzionalità limita l'azione pubblica."},
  {s:"La Commission ouvre une procédure d'infraction.",                 it:"La Commissione avvia una procedura d'infrazione."},
  {s:"Le requérant invoque une violation de ses droits.",               it:"Il ricorrente invoca una violazione dei suoi diritti."},
  {s:"Le tribunal ordonne une expertise judiciaire.",                   it:"Il tribunale ordina una perizia giudiziaria."},
  {s:"La prescription éteint l'action publique.",                       it:"La prescrizione estingue l'azione penale."},
  {s:"Les États membres coordonnent leurs politiques économiques.",     it:"Gli Stati membri coordinano le loro politiche economiche."},
  {s:"Le Conseil européen fixe les orientations générales.",            it:"Il Consiglio europeo definisce gli orientamenti generali."},
  {s:"La clause abusive est réputée non écrite.",                       it:"La clausola abusiva si considera non apposta."},
  {s:"Le créancier peut exiger l'exécution forcée.",                    it:"Il creditore può esigere l'esecuzione forzata."},
  {s:"L'avocat général présente ses conclusions.",                      it:"L'avvocato generale presenta le sue conclusioni."},
  {s:"La liberté d'expression connaît certaines limites.",              it:"La libertà di espressione conosce alcuni limiti."},
  {s:"Le maire prend un arrêté municipal.",                             it:"Il sindaco emana un'ordinanza comunale."},
  {s:"La responsabilité civile suppose un dommage.",                    it:"La responsabilità civile presuppone un danno."},
  {s:"Le témoin prête serment devant la cour.",                         it:"Il testimone presta giuramento davanti alla corte."},
  {s:"Le traité de Lisbonne a réformé les institutions.",               it:"Il trattato di Lisbona ha riformato le istituzioni."},
  {s:"La citoyenneté européenne complète la nationalité.",              it:"La cittadinanza europea integra la nazionalità."},
  {s:"Le juge applique le principe du contradictoire.",                 it:"Il giudice applica il principio del contraddittorio."},
  {s:"L'amende administrative sanctionne le manquement.",               it:"La sanzione amministrativa punisce l'inadempienza."},
  {s:"La médiation évite souvent un procès long.",                      it:"La mediazione evita spesso un processo lungo."},
  {s:"Les parties signent un protocole d'accord.",                      it:"Le parti firmano un protocollo d'intesa."},
  {s:"La cour vérifie la régularité de la procédure.",                  it:"La corte verifica la regolarità della procedura."},
  {s:"Le droit d'asile est garanti par la Constitution.",               it:"Il diritto d'asilo è garantito dalla Costituzione."},
  {s:"L'audience se déroule à huis clos.",                              it:"L'udienza si svolge a porte chiuse."},
  {s:"Le recours en annulation vise l'acte illégal.",                   it:"Il ricorso di annullamento riguarda l'atto illegittimo."},
];
const LAW_LEN = 8;

/* ---- Level 5 / 💼 Au bureau — the everyday French of a working day in a law
   firm. Not legal language: the phone, the deadline, the printer, the coffee.
   This is the half of the job the textbooks skip. ---- */
const OFFICE_SENTENCES = [
  {s:"Bonjour, je viens pour le rendez-vous de neuf heures.",           it:"Buongiorno, vengo per l'appuntamento delle nove."},
  {s:"Pourriez-vous me transférer l'appel, s'il vous plaît ?",          it:"Potrebbe trasferirmi la chiamata, per favore?"},
  {s:"Je vous envoie le dossier par courriel avant midi.",              it:"Le invio il fascicolo per email entro mezzogiorno."},
  {s:"La réunion est reportée à jeudi après-midi.",                     it:"La riunione è rinviata a giovedì pomeriggio."},
  {s:"Avez-vous relu le contrat que je vous ai transmis ?",             it:"Ha riletto il contratto che le ho trasmesso?"},
  {s:"Le client souhaite un point d'étape cette semaine.",              it:"Il cliente desidera un aggiornamento questa settimana."},
  {s:"Je suis en télétravail lundi et mardi.",                          it:"Lavoro da remoto lunedì e martedì."},
  {s:"L'imprimante est en panne, j'appelle le service technique.",      it:"La stampante è guasta, chiamo l'assistenza tecnica."},
  {s:"Pouvez-vous me rappeler dans une dizaine de minutes ?",           it:"Può richiamarmi tra una decina di minuti?"},
  {s:"Le délai est fixé au trente du mois.",                            it:"La scadenza è fissata al trenta del mese."},
  {s:"Je vais préparer une note de synthèse pour l'associé.",           it:"Preparo una nota di sintesi per il socio."},
  {s:"N'oubliez pas de signer le parapheur avant de partir.",           it:"Non dimentichi di firmare la cartella firme prima di andare."},
  {s:"Nous devons facturer ces heures au client.",                      it:"Dobbiamo fatturare queste ore al cliente."},
  {s:"La secrétaire a classé les pièces du dossier.",                   it:"La segretaria ha archiviato i documenti del fascicolo."},
  {s:"Je prends un café, vous en voulez un ?",                          it:"Prendo un caffè, ne vuole uno?"},
  {s:"Le stagiaire commence lundi prochain.",                           it:"Il tirocinante inizia lunedì prossimo."},
  {s:"Il faut déposer les conclusions avant vendredi.",                 it:"Bisogna depositare le conclusioni entro venerdì."},
  {s:"Je suis désolé, je suis en retard à cause du trafic.",            it:"Mi scusi, sono in ritardo a causa del traffico."},
  {s:"Pourriez-vous me faire une copie de ce document ?",               it:"Potrebbe farmi una copia di questo documento?"},
  {s:"La salle de réunion est occupée jusqu'à quinze heures.",          it:"La sala riunioni è occupata fino alle quindici."},
  {s:"Je vous mets en copie de l'échange.",                             it:"La metto in copia nello scambio."},
  {s:"Le rendez-vous chez le notaire est confirmé.",                    it:"L'appuntamento dal notaio è confermato."},
  {s:"Merci de votre retour rapide sur ce point.",                      it:"Grazie per il suo rapido riscontro su questo punto."},
  {s:"Nous allons planifier un appel avec l'équipe.",                   it:"Organizzeremo una chiamata con il team."},
  {s:"Le budget de la mission a été validé.",                           it:"Il budget dell'incarico è stato approvato."},
  {s:"Je n'ai pas reçu la pièce jointe, pouvez-vous la renvoyer ?",     it:"Non ho ricevuto l'allegato, può rinviarlo?"},
  {s:"Bonne journée, et à demain.",                                     it:"Buona giornata, e a domani."},
  {s:"Le cabinet ferme à dix-neuf heures.",                             it:"Lo studio chiude alle diciannove."},
  {s:"Je dois relire les statuts de la société.",                       it:"Devo rileggere lo statuto della società."},
  {s:"L'audience a été fixée au mois prochain.",                        it:"L'udienza è stata fissata al mese prossimo."},
  {s:"Je vous propose de déjeuner ensemble mercredi.",                  it:"Le propongo di pranzare insieme mercoledì."},
  {s:"Le rapport doit être finalisé pour ce soir.",                     it:"Il rapporto deve essere finalizzato per stasera."},
  {s:"Pouvez-vous vérifier les coordonnées du client ?",                it:"Può verificare i recapiti del cliente?"},
  {s:"J'ai bien reçu votre message, je m'en occupe.",                   it:"Ho ricevuto il suo messaggio, me ne occupo."},
  {s:"La facture sera envoyée en fin de mois.",                         it:"La fattura sarà inviata a fine mese."},
  {s:"Je vais chercher le dossier aux archives.",                       it:"Vado a prendere il fascicolo in archivio."},
  {s:"Nous attendons la réponse de la partie adverse.",                 it:"Aspettiamo la risposta della controparte."},
  {s:"Le contrat doit être relu par un confrère.",                      it:"Il contratto deve essere riletto da un collega."},
  {s:"Excusez-moi, pourriez-vous répéter plus lentement ?",             it:"Mi scusi, potrebbe ripetere più lentamente?"},
  {s:"Je vous remercie de votre confiance.",                            it:"La ringrazio per la sua fiducia."},
];


/* ---- Level 6: enter / train a custom sentence ---- */
const SENT_EXAMPLES = [
  "La liberté des uns s'arrête là où commence celle des autres.",
  "Je voudrais réserver une table pour deux personnes à vingt heures.",
  "Les grenouilles vertes coassent au bord de l'étang.",
  "Mon oncle habite un vieux village au cœur des montagnes."
];

export { LEVEL1, LEVEL2, LEVEL3, TRANS, ODD, LAW_SENTENCES, OFFICE_SENTENCES, LAW_LEN, SENT_EXAMPLES };
