/* Écoute — all the teaching content, and nothing else.

   Split out of french-sounds.html so the material can be edited without reading
   a line of app code: add a minimal pair here and the course picks it up on its
   own (the `focus` field IS the lesson id — see contrastKey() in the app).

   Loaded as a plain classic script before the app, so everything below is a
   global. No build step, no imports, nothing to compile. */


/* ===========================================================
   DATA — every French vowel phoneme is covered across the set.
   Oral:  i y u e ɛ ø œ ə a o ɔ
   Nasal: ɑ̃ ɛ̃ ɔ̃ œ̃
   Each item: prompt (what is spoken), options, answer index, focus, ipa
   =========================================================== */

const LEVEL1 = [
  {p:"chat",  o:["chat","chien"],  a:0, focus:"/a/ vs /jɛ̃/", ipa:"chat /ʃa/ · chien /ʃjɛ̃/"},
  {p:"son",   o:["son","sang"],    a:0, focus:"/ɔ̃/ vs /ɑ̃/",  ipa:"son /sɔ̃/ · sang /sɑ̃/"},
  {p:"tout",  o:["tout","tu"],     a:0, focus:"/u/ vs /y/",   ipa:"tout /tu/ · tu /ty/"},
  {p:"roue",  o:["roue","rue"],    a:0, focus:"/u/ vs /y/",   ipa:"roue /ʁu/ · rue /ʁy/"},
  {p:"nous",  o:["nous","nu"],     a:0, focus:"/u/ vs /y/",   ipa:"nous /nu/ · nu /ny/"},
  {p:"vous",  o:["vous","vu"],     a:0, focus:"/u/ vs /y/",   ipa:"vous /vu/ · vu /vy/"},
  {p:"vie",   o:["vie","vue"],     a:0, focus:"/i/ vs /y/",   ipa:"vie /vi/ · vue /vy/"},
  {p:"si",    o:["si","su"],       a:0, focus:"/i/ vs /y/",   ipa:"si /si/ · su /sy/"},
  {p:"lit",   o:["lit","lu"],      a:0, focus:"/i/ vs /y/",   ipa:"lit /li/ · lu /ly/"},
  {p:"beau",  o:["beau","bon"],    a:0, focus:"/o/ vs /ɔ̃/",   ipa:"beau /bo/ · bon /bɔ̃/"},
  {p:"mot",   o:["mot","mon"],     a:0, focus:"/o/ vs /ɔ̃/",   ipa:"mot /mo/ · mon /mɔ̃/"},
  {p:"dos",   o:["dos","don"],     a:0, focus:"/o/ vs /ɔ̃/",   ipa:"dos /do/ · don /dɔ̃/"},
  {p:"seau",  o:["seau","son"],    a:0, focus:"/o/ vs /ɔ̃/",   ipa:"seau /so/ · son /sɔ̃/"},
  {p:"faux",  o:["faux","fond"],   a:0, focus:"/o/ vs /ɔ̃/",   ipa:"faux /fo/ · fond /fɔ̃/"},
  {p:"pain",  o:["pain","pont"],   a:0, focus:"/ɛ̃/ vs /ɔ̃/",   ipa:"pain /pɛ̃/ · pont /pɔ̃/"},
  {p:"bain",  o:["bain","bon"],    a:0, focus:"/ɛ̃/ vs /ɔ̃/",   ipa:"bain /bɛ̃/ · bon /bɔ̃/"},
  {p:"fin",   o:["fin","font"],    a:0, focus:"/ɛ̃/ vs /ɔ̃/",   ipa:"fin /fɛ̃/ · font /fɔ̃/"},
  {p:"vin",   o:["vin","vent"],    a:0, focus:"/ɛ̃/ vs /ɑ̃/",   ipa:"vin /vɛ̃/ · vent /vɑ̃/"},
  {p:"main",  o:["main","ment"],   a:0, focus:"/ɛ̃/ vs /ɑ̃/",   ipa:"main /mɛ̃/ · ment /mɑ̃/"},
  {p:"rond",  o:["rond","rang"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"rond /ʁɔ̃/ · rang /ʁɑ̃/"},
  {p:"bon",   o:["bon","banc"],    a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"bon /bɔ̃/ · banc /bɑ̃/"},
  {p:"long",  o:["long","lent"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"long /lɔ̃/ · lent /lɑ̃/"},
  {p:"blond", o:["blond","blanc"], a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"blond /blɔ̃/ · blanc /blɑ̃/"},
  {p:"ton",   o:["ton","temps"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/",   ipa:"ton /tɔ̃/ · temps /tɑ̃/"},
  {p:"sa",    o:["sa","sans"],     a:0, focus:"/a/ vs /ɑ̃/",   ipa:"sa /sa/ · sans /sɑ̃/"},
  {p:"ça",    o:["ça","cent"],     a:0, focus:"/a/ vs /ɑ̃/",   ipa:"ça /sa/ · cent /sɑ̃/"},
  {p:"va",    o:["va","vent"],     a:0, focus:"/a/ vs /ɑ̃/",   ipa:"va /va/ · vent /vɑ̃/"},
  {p:"peur",  o:["peur","peu"],    a:0, focus:"/œ/ vs /ø/",   ipa:"peur /pœʁ/ · peu /pø/"},
  {p:"sœur",  o:["sœur","ceux"],   a:0, focus:"/œ/ vs /ø/",   ipa:"sœur /sœʁ/ · ceux /sø/"},
  {p:"jeune", o:["jeune","jeu"],   a:0, focus:"/œ/ vs /ø/",   ipa:"jeune /ʒœn/ · jeu /ʒø/"},
  // simple oral-vowel pairs (chat/chaud family)
  {p:"chat",  o:["chat","chaud"],  a:0, focus:"/a/ vs /o/",   ipa:"chat /ʃa/ · chaud /ʃo/"},
  {p:"bas",   o:["bas","beau"],    a:0, focus:"/a/ vs /o/",   ipa:"bas /ba/ · beau /bo/"},
  {p:"ma",    o:["ma","mot"],      a:0, focus:"/a/ vs /o/",   ipa:"ma /ma/ · mot /mo/"},
  {p:"ta",    o:["ta","tôt"],      a:0, focus:"/a/ vs /o/",   ipa:"ta /ta/ · tôt /to/"},
  {p:"pas",   o:["pas","peau"],    a:0, focus:"/a/ vs /o/",   ipa:"pas /pa/ · peau /po/"},
  {p:"gras",  o:["gras","gros"],   a:0, focus:"/a/ vs /o/",   ipa:"gras /ɡʁa/ · gros /ɡʁo/"},
  {p:"tout",  o:["tout","tôt"],    a:0, focus:"/u/ vs /o/",   ipa:"tout /tu/ · tôt /to/"},
  {p:"sous",  o:["sous","seau"],   a:0, focus:"/u/ vs /o/",   ipa:"sous /su/ · seau /so/"},
  {p:"loup",  o:["loup","lu"],     a:0, focus:"/u/ vs /y/",   ipa:"loup /lu/ · lu /ly/"},
  {p:"joue",  o:["joue","jus"],    a:0, focus:"/u/ vs /y/",   ipa:"joue /ʒu/ · jus /ʒy/"},
  {p:"boue",  o:["boue","bu"],     a:0, focus:"/u/ vs /y/",   ipa:"boue /bu/ · bu /by/"},
  {p:"cou",   o:["cou","queue"],   a:0, focus:"/u/ vs /ø/",   ipa:"cou /ku/ · queue /kø/"},
  {p:"lit",   o:["lit","les"],     a:0, focus:"/i/ vs /e/",   ipa:"lit /li/ · les /le/"},
  {p:"ni",    o:["ni","nez"],      a:0, focus:"/i/ vs /e/",   ipa:"ni /ni/ · nez /ne/"},
  {p:"dit",   o:["dit","des"],     a:0, focus:"/i/ vs /e/",   ipa:"dit /di/ · des /de/"},
  {p:"mes",   o:["mes","mais"],    a:0, focus:"/e/ vs /ɛ/",   ipa:"mes /me/ · mais /mɛ/"},
  {p:"les",   o:["les","lait"],    a:0, focus:"/e/ vs /ɛ/",   ipa:"les /le/ · lait /lɛ/"},
  {p:"peu",   o:["peu","peau"],    a:0, focus:"/ø/ vs /o/",   ipa:"peu /pø/ · peau /po/"},
  {p:"deux",  o:["deux","dos"],    a:0, focus:"/ø/ vs /o/",   ipa:"deux /dø/ · dos /do/"},
  {p:"feu",   o:["feu","faux"],    a:0, focus:"/ø/ vs /o/",   ipa:"feu /fø/ · faux /fo/"},
];

// Level 2 — longer (multi-syllable) words, same clear contrasts.
const LEVEL2 = [
  {p:"bateau",  o:["bateau","bâton"],     a:0, focus:"/o/ vs /ɔ̃/",  ipa:"bateau /bato/ · bâton /batɔ̃/"},
  {p:"manteau", o:["manteau","menton"],   a:0, focus:"/o/ vs /ɔ̃/",  ipa:"manteau /mɑ̃to/ · menton /mɑ̃tɔ̃/"},
  {p:"chapeau", o:["chapeau","chapon"],   a:0, focus:"/o/ vs /ɔ̃/",  ipa:"chapeau /ʃapo/ · chapon /ʃapɔ̃/"},
  {p:"oiseau",  o:["oiseau","oison"],     a:0, focus:"/o/ vs /ɔ̃/",  ipa:"oiseau /wazo/ · oison /wazɔ̃/"},
  {p:"drapeau", o:["drapeau","drapons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"drapeau /dʁapo/ · drapons /dʁapɔ̃/"},
  {p:"couteau", o:["couteau","coûtons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"couteau /kuto/ · coûtons /kutɔ̃/"},
  {p:"rideau",  o:["rideau","ridons"],    a:0, focus:"/o/ vs /ɔ̃/",  ipa:"rideau /ʁido/ · ridons /ʁidɔ̃/"},
  {p:"cerveau", o:["cerveau","servons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"cerveau /sɛʁvo/ · servons /sɛʁvɔ̃/"},
  {p:"noyau",   o:["noyau","noyons"],     a:0, focus:"/o/ vs /ɔ̃/",  ipa:"noyau /nwajo/ · noyons /nwajɔ̃/"},
  {p:"berceau", o:["berceau","berçons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"berceau /bɛʁso/ · berçons /bɛʁsɔ̃/"},
  {p:"marron",  o:["marron","marrant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"marron /maʁɔ̃/ · marrant /maʁɑ̃/"},
  {p:"savon",   o:["savon","savant"],     a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"savon /savɔ̃/ · savant /savɑ̃/"},
  {p:"menton",  o:["menton","mentant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"menton /mɑ̃tɔ̃/ · mentant /mɑ̃tɑ̃/"},
  {p:"ballon",  o:["ballon","ballant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"ballon /balɔ̃/ · ballant /balɑ̃/"},
  {p:"bouchon", o:["bouchon","bouchant"], a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"bouchon /buʃɔ̃/ · bouchant /buʃɑ̃/"},
  {p:"glaçon",  o:["glaçon","glaçant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"glaçon /ɡlasɔ̃/ · glaçant /ɡlasɑ̃/"},
  {p:"maçon",   o:["maçon","massant"],    a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"maçon /masɔ̃/ · massant /masɑ̃/"},
  {p:"cochon",  o:["cochon","cachant"],   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"cochon /kɔʃɔ̃/ · cachant /kaʃɑ̃/"},
  {p:"torchon", o:["torchon","torchant"], a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"torchon /tɔʁʃɔ̃/ · torchant /tɔʁʃɑ̃/"},
  {p:"blouson", o:["blouson","blousant"], a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"blouson /bluzɔ̃/ · blousant /bluzɑ̃/"},
  {p:"flocon",  o:["flocon","floquant"],  a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"flocon /flɔkɔ̃/ · floquant /flɔkɑ̃/"},
  {p:"melon",   o:["melon","mêlant"],     a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"melon /məlɔ̃/ · mêlant /mɛlɑ̃/"},
  {p:"jeton",   o:["jeton","jetant"],     a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"jeton /ʒətɔ̃/ · jetant /ʒətɑ̃/"},
  {p:"raisin",  o:["raisin","raison"],    a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"raisin /ʁɛzɛ̃/ · raison /ʁɛzɔ̃/"},
  {p:"lapin",   o:["lapin","lapon"],      a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"lapin /lapɛ̃/ · lapon /lapɔ̃/"},
  {p:"bassin",  o:["bassin","basson"],    a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"bassin /basɛ̃/ · basson /basɔ̃/"},
  {p:"moulin",  o:["moulin","moulons"],   a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"moulin /mulɛ̃/ · moulons /mulɔ̃/"},
  {p:"ami",     o:["ami","amant"],        a:0, focus:"/i/ vs /ɑ̃/",  ipa:"ami /ami/ · amant /amɑ̃/"},
  {p:"dessus",  o:["dessus","dessous"],   a:0, focus:"/y/ vs /u/",  ipa:"dessus /dəsy/ · dessous /dəsu/"},
  {p:"ici",     o:["ici","issu"],         a:0, focus:"/i/ vs /y/",  ipa:"ici /isi/ · issu /isy/"},
  // voicing /s/ vs /z/ and other simple multi-syllable contrasts
  {p:"coussin", o:["coussin","cousin"],   a:0, focus:"/s/ vs /z/",  ipa:"coussin /kusɛ̃/ · cousin /kuzɛ̃/"},
  {p:"poisson", o:["poisson","poison"],   a:0, focus:"/s/ vs /z/",  ipa:"poisson /pwasɔ̃/ · poison /pwazɔ̃/"},
  {p:"dessert", o:["dessert","désert"],   a:0, focus:"/s/ vs /z/",  ipa:"dessert /desɛʁ/ · désert /dezɛʁ/"},
  {p:"cheveux", o:["cheveux","chevaux"],  a:0, focus:"/ø/ vs /o/",  ipa:"cheveux /ʃəvø/ · chevaux /ʃəvo/"},
  {p:"château", o:["château","chatons"],  a:0, focus:"/o/ vs /ɔ̃/",  ipa:"château /ʃato/ · chatons /ʃatɔ̃/"},
  {p:"été",     o:["été","était"],        a:0, focus:"/e/ vs /ɛ/",  ipa:"été /ete/ · était /etɛ/"},
];

// Level 3 — the same sounds inside full sentences.
const LEVEL3 = [
  {p:"J'ai promené mon chat.",        o:["J'ai promené mon chat.","J'ai promené mon chien."],         a:0, focus:"/a/ vs /jɛ̃/", ipa:"chat /ʃa/ · chien /ʃjɛ̃/"},
  {p:"Il a marqué le but.",           o:["Il a marqué le but.","Il a marqué le bout."],               a:0, focus:"/y/ vs /u/",  ipa:"but /by/ · bout /bu/"},
  {p:"La roue tourne lentement.",     o:["La roue tourne lentement.","La rue tourne lentement."],     a:0, focus:"/u/ vs /y/",  ipa:"roue /ʁu/ · rue /ʁy/"},
  {p:"J'adore cette vue.",            o:["J'adore cette vue.","J'adore cette vie."],                  a:0, focus:"/y/ vs /i/",  ipa:"vue /vy/ · vie /vi/"},
  {p:"Le chat dort dessus.",          o:["Le chat dort dessus.","Le chat dort dessous."],            a:0, focus:"/y/ vs /u/",  ipa:"dessus /dəsy/ · dessous /dəsu/"},
  {p:"Il vend des pulls.",            o:["Il vend des pulls.","Il vend des poules."],                 a:0, focus:"/y/ vs /u/",  ipa:"pull /pyl/ · poule /pul/"},
  {p:"Il a très peu.",                o:["Il a très peu.","Il a très peur."],                         a:0, focus:"/ø/ vs /œ/",  ipa:"peu /pø/ · peur /pœʁ/"},
  {p:"Le bateau est grand.",          o:["Le bateau est grand.","Le bâton est grand."],               a:0, focus:"/o/ vs /ɔ̃/",  ipa:"bateau /bato/ · bâton /batɔ̃/"},
  {p:"Il porte un manteau marron.",   o:["Il porte un manteau marron.","Il porte un manteau marrant."], a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"marron /maʁɔ̃/ · marrant /maʁɑ̃/"},
  {p:"C'est un bon savon.",           o:["C'est un bon savon.","C'est un bon savant."],               a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"savon /savɔ̃/ · savant /savɑ̃/"},
  {p:"Le train est là.",              o:["Le train est là.","Le train est lent."],                   a:0, focus:"/a/ vs /ɑ̃/",  ipa:"là /la/ · lent /lɑ̃/"},
  {p:"Il passe à toi.",               o:["Il passe à toi.","Il pense à toi."],                        a:0, focus:"/a/ vs /ɑ̃/",  ipa:"passe /pas/ · pense /pɑ̃s/"},
  {p:"Il fait du vin.",               o:["Il fait du vin.","Il fait du vent."],                       a:0, focus:"/ɛ̃/ vs /ɑ̃/", ipa:"vin /vɛ̃/ · vent /vɑ̃/"},
  {p:"Il peint le mur.",              o:["Il peint le mur.","Il pend le mur."],                       a:0, focus:"/ɛ̃/ vs /ɑ̃/", ipa:"peint /pɛ̃/ · pend /pɑ̃/"},
  {p:"C'est un beau gâteau.",         o:["C'est un beau gâteau.","C'est un bon gâteau."],             a:0, focus:"/o/ vs /ɔ̃/",  ipa:"beau /bo/ · bon /bɔ̃/"},
  {p:"C'est mon seau.",               o:["C'est mon seau.","C'est mon son."],                         a:0, focus:"/o/ vs /ɔ̃/",  ipa:"seau /so/ · son /sɔ̃/"},
  {p:"Il a les cheveux blancs.",      o:["Il a les cheveux blancs.","Il a les cheveux blonds."],      a:0, focus:"/ɑ̃/ vs /ɔ̃/", ipa:"blanc /blɑ̃/ · blond /blɔ̃/"},
  {p:"Dessine un rond.",              o:["Dessine un rond.","Dessine un rang."],                      a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"rond /ʁɔ̃/ · rang /ʁɑ̃/"},
  {p:"Le film est long.",             o:["Le film est long.","Le film est lent."],                   a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"long /lɔ̃/ · lent /lɑ̃/"},
  {p:"Le chien ronge l'os.",          o:["Le chien ronge l'os.","Le chien range l'os."],              a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"ronge /ʁɔ̃ʒ/ · range /ʁɑ̃ʒ/"},
  {p:"C'est une forte pente.",        o:["C'est une forte pente.","C'est une forte ponte."],          a:0, focus:"/ɑ̃/ vs /ɔ̃/", ipa:"pente /pɑ̃t/ · ponte /pɔ̃t/"},
  {p:"Quel beau teint !",             o:["Quel beau teint !","Quel beau ton !"],                      a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"teint /tɛ̃/ · ton /tɔ̃/"},
  {p:"Je vois le train.",             o:["Je vois le train.","Je vois le tronc."],                    a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"train /tʁɛ̃/ · tronc /tʁɔ̃/"},
  {p:"C'est un grand pin.",           o:["C'est un grand pin.","C'est un grand pont."],               a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"pin /pɛ̃/ · pont /pɔ̃/"},
  {p:"J'aime le raisin.",             o:["J'aime le raisin.","J'aime la raison."],                    a:0, focus:"/ɛ̃/ vs /ɔ̃/", ipa:"raisin /ʁɛzɛ̃/ · raison /ʁɛzɔ̃/"},
  {p:"Le pont est solide.",           o:["Le pont est solide.","Le pan est solide."],                 a:0, focus:"/ɔ̃/ vs /ɑ̃/", ipa:"pont /pɔ̃/ · pan /pɑ̃/"},
  {p:"Quel beau banc !",              o:["Quel beau banc !","Quel beau bond !"],                      a:0, focus:"/ɑ̃/ vs /ɔ̃/", ipa:"banc /bɑ̃/ · bond /bɔ̃/"},
  {p:"C'est une jolie rue.",          o:["C'est une jolie rue.","C'est une jolie roue."],             a:0, focus:"/y/ vs /u/",  ipa:"rue /ʁy/ · roue /ʁu/"},
  {p:"Quel bon vin !",                o:["Quel bon vin !","Quel bon vent !"],                         a:0, focus:"/ɛ̃/ vs /ɑ̃/", ipa:"vin /vɛ̃/ · vent /vɑ̃/"},
  {p:"Quel joli chapeau !",           o:["Quel joli chapeau !","Quel joli chapon !"],                 a:0, focus:"/o/ vs /ɔ̃/",  ipa:"chapeau /ʃapo/ · chapon /ʃapɔ̃/"},
  {p:"J'ai mangé du poisson.",        o:["J'ai mangé du poisson.","J'ai mangé du poison."],           a:0, focus:"/s/ vs /z/",  ipa:"poisson /pwasɔ̃/ · poison /pwazɔ̃/"},
  {p:"C'est mon cousin.",             o:["C'est mon cousin.","C'est mon coussin."],                   a:0, focus:"/z/ vs /s/",  ipa:"cousin /kuzɛ̃/ · coussin /kusɛ̃/"},
  {p:"Elle a de beaux cheveux.",      o:["Elle a de beaux cheveux.","Elle a de beaux chevaux."],      a:0, focus:"/ø/ vs /o/",  ipa:"cheveux /ʃəvø/ · chevaux /ʃəvo/"},
  {p:"Le dessert est bon.",           o:["Le dessert est bon.","Le désert est bon."],                 a:0, focus:"/s/ vs /z/",  ipa:"dessert /desɛʁ/ · désert /dezɛʁ/"},
  {p:"C'est trop gras.",              o:["C'est trop gras.","C'est trop gros."],                      a:0, focus:"/a/ vs /o/",  ipa:"gras /ɡʁa/ · gros /ɡʁo/"},
];

/* ===== Italian translations (shown under each French word / sentence) ===== */
const TRANS = {
  // Level 1 — words
  "chat":"gatto","chien":"cane","son":"suono","sang":"sangue","tout":"tutto","tu":"tu",
  "roue":"ruota","rue":"strada","nous":"noi","nu":"nudo","vous":"voi","vu":"visto",
  "vie":"vita","vue":"vista","si":"se","su":"saputo","lit":"letto","lu":"letto (p.p.)",
  "beau":"bello","bon":"buono","mot":"parola","mon":"mio","dos":"schiena","don":"dono",
  "seau":"secchio","faux":"falso","fond":"fondo","pain":"pane","pont":"ponte","bain":"bagno",
  "fin":"fine","font":"fanno","vin":"vino","vent":"vento","main":"mano","ment":"mente",
  "rond":"tondo","rang":"fila","banc":"panca","long":"lungo","lent":"lento","blond":"biondo",
  "blanc":"bianco","ton":"tono","temps":"tempo","sa":"sua","sans":"senza","ça":"questo",
  "cent":"cento","va":"va","peur":"paura","peu":"poco","sœur":"sorella","ceux":"quelli",
  "jeune":"giovane","jeu":"gioco",
  // Level 1 — new simple pairs
  "chaud":"caldo","bas":"basso","ma":"mia","ta":"tua","tôt":"presto","pas":"passo",
  "peau":"pelle","gras":"grasso","gros":"grosso","sous":"sotto","loup":"lupo","joue":"guancia",
  "jus":"succo","boue":"fango","bu":"bevuto","cou":"collo","queue":"coda","les":"i / gli",
  "ni":"né","nez":"naso","dit":"detto","des":"dei / degli","mes":"miei","mais":"ma",
  "lait":"latte","deux":"due","feu":"fuoco",
  // Level 2 — longer words
  "bateau":"barca","bâton":"bastone","manteau":"cappotto","menton":"mento","chapeau":"cappello",
  "chapon":"cappone","oiseau":"uccello","oison":"papero","drapeau":"bandiera","drapons":"(noi) drappeggiamo",
  "couteau":"coltello","coûtons":"(noi) costiamo","rideau":"tenda","ridons":"(noi) ridiamo",
  "cerveau":"cervello","servons":"(noi) serviamo","noyau":"nocciolo","noyons":"(noi) anneghiamo",
  "berceau":"culla","berçons":"(noi) culliamo","marron":"marrone","marrant":"divertente",
  "savon":"sapone","savant":"sapiente","mentant":"(che) mente","ballon":"pallone","ballant":"penzolante",
  "bouchon":"tappo","bouchant":"(che) tappa","glaçon":"cubetto di ghiaccio","glaçant":"agghiacciante",
  "maçon":"muratore","massant":"(che) massaggia","cochon":"maiale","cachant":"(che) nasconde",
  "torchon":"straccio","torchant":"(che) pulisce","blouson":"giubbotto","blousant":"(che) si gonfia",
  "flocon":"fiocco","floquant":"(che) riveste","melon":"melone","mêlant":"(che) mescola",
  "jeton":"gettone","jetant":"(che) getta","raisin":"uva","raison":"ragione","lapin":"coniglio",
  "lapon":"lappone","bassin":"bacino","basson":"fagotto","moulin":"mulino","moulons":"(noi) maciniamo",
  "ami":"amico","amant":"amante","dessus":"sopra","dessous":"sotto","ici":"qui","issu":"derivato",
  "coussin":"cuscino","cousin":"cugino","poisson":"pesce","poison":"veleno","dessert":"dolce",
  "désert":"deserto","cheveux":"capelli","chevaux":"cavalli","château":"castello","chatons":"gattini",
  "été":"estate","était":"era",
  // Level 3 — sentences
  "J'ai promené mon chat.":"Ho portato a spasso il mio gatto.",
  "J'ai promené mon chien.":"Ho portato a spasso il mio cane.",
  "Il a marqué le but.":"Ha segnato il gol.",
  "Il a marqué le bout.":"Ha marcato l'estremità.",
  "La roue tourne lentement.":"La ruota gira lentamente.",
  "La rue tourne lentement.":"La strada gira lentamente.",
  "J'adore cette vue.":"Adoro questa vista.",
  "J'adore cette vie.":"Adoro questa vita.",
  "Le chat dort dessus.":"Il gatto dorme sopra.",
  "Le chat dort dessous.":"Il gatto dorme sotto.",
  "Il vend des pulls.":"Vende dei maglioni.",
  "Il vend des poules.":"Vende delle galline.",
  "Il a très peu.":"Ne ha molto poco.",
  "Il a très peur.":"Ha molta paura.",
  "Le bateau est grand.":"La barca è grande.",
  "Le bâton est grand.":"Il bastone è grande.",
  "Il porte un manteau marron.":"Indossa un cappotto marrone.",
  "Il porte un manteau marrant.":"Indossa un cappotto divertente.",
  "C'est un bon savon.":"È un buon sapone.",
  "C'est un bon savant.":"È un buon sapiente.",
  "Le train est là.":"Il treno è qui.",
  "Le train est lent.":"Il treno è lento.",
  "Il passe à toi.":"Tocca a te.",
  "Il pense à toi.":"Pensa a te.",
  "Il fait du vin.":"Fa il vino.",
  "Il fait du vent.":"Tira vento.",
  "Il peint le mur.":"Dipinge il muro.",
  "Il pend le mur.":"Appende il muro.",
  "C'est un beau gâteau.":"È una bella torta.",
  "C'est un bon gâteau.":"È una buona torta.",
  "C'est mon seau.":"È il mio secchio.",
  "C'est mon son.":"È il mio suono.",
  "Il a les cheveux blancs.":"Ha i capelli bianchi.",
  "Il a les cheveux blonds.":"Ha i capelli biondi.",
  "Dessine un rond.":"Disegna un cerchio.",
  "Dessine un rang.":"Disegna una fila.",
  "Le film est long.":"Il film è lungo.",
  "Le film est lent.":"Il film è lento.",
  "Le chien ronge l'os.":"Il cane rosicchia l'osso.",
  "Le chien range l'os.":"Il cane mette a posto l'osso.",
  "C'est une forte pente.":"È una forte pendenza.",
  "C'est une forte ponte.":"È una grande covata.",
  "Quel beau teint !":"Che bel colorito!",
  "Quel beau ton !":"Che bel tono!",
  "Je vois le train.":"Vedo il treno.",
  "Je vois le tronc.":"Vedo il tronco.",
  "C'est un grand pin.":"È un grande pino.",
  "C'est un grand pont.":"È un grande ponte.",
  "J'aime le raisin.":"Mi piace l'uva.",
  "J'aime la raison.":"Amo la ragione.",
  "Le pont est solide.":"Il ponte è solido.",
  "Le pan est solide.":"Il lembo è solido.",
  "Quel beau banc !":"Che bella panchina!",
  "Quel beau bond !":"Che bel balzo!",
  "C'est une jolie rue.":"È una bella strada.",
  "C'est une jolie roue.":"È una bella ruota.",
  "Quel bon vin !":"Che buon vino!",
  "Quel bon vent !":"Che buon vento!",
  "Quel joli chapeau !":"Che bel cappello!",
  "Quel joli chapon !":"Che bel cappone!",
  "J'ai mangé du poisson.":"Ho mangiato del pesce.",
  "J'ai mangé du poison.":"Ho mangiato del veleno.",
  "C'est mon cousin.":"È mio cugino.",
  "C'est mon coussin.":"È il mio cuscino.",
  "Elle a de beaux cheveux.":"Ha bei capelli.",
  "Elle a de beaux chevaux.":"Ha bei cavalli.",
  "Le dessert est bon.":"Il dolce è buono.",
  "Le désert est bon.":"Il deserto è buono.",
  "C'est trop gras.":"È troppo grasso.",
  "C'est trop gros.":"È troppo grosso.",
};

/* ===== "Odd" prompts =====
   Grammatically correct but not something you'd normally say — they exist only
   to give a clean minimal pair for the sound. After the user answers we flag
   these so they know the phrase isn't meant to make real-world sense. */
const ODD = new Set([
  // Level 2 — real "nous" verb forms, but you'd never say them on their own
  "drapons","coûtons","ridons","servons","noyons","berçons","moulons",
  // Level 3 — the semantically odd half of each sentence pair
  "Il a marqué le bout.","La rue tourne lentement.","Il porte un manteau marrant.",
  "Il pend le mur.","C'est mon son.","Le chien range l'os.","C'est une forte ponte.",
  "Le pan est solide.","Quel joli chapon !","J'ai mangé du poison.","Le désert est bon.",
]);

/* ---- Level 5 — read aloud full sentences about French / European law ---- */
const LAW_SENTENCES = [
  {s:"Le Parlement européen adopte de nouvelles directives.",            it:"Il Parlamento europeo adotta nuove direttive."},
  {s:"La Cour de cassation a rendu son arrêt hier.",                     it:"La Corte di cassazione ha emesso la sentenza ieri."},
  {s:"Le Conseil constitutionnel vérifie la conformité des lois.",       it:"Il Consiglio costituzionale verifica la conformità delle leggi."},
  {s:"Chaque citoyen européen bénéficie de la libre circulation.",       it:"Ogni cittadino europeo beneficia della libera circolazione."},
  {s:"Le droit communautaire prime sur le droit national.",              it:"Il diritto comunitario prevale sul diritto nazionale."},
  {s:"La Commission européenne propose un nouveau règlement.",           it:"La Commissione europea propone un nuovo regolamento."},
  {s:"Les traités garantissent les droits fondamentaux des personnes.",  it:"I trattati garantiscono i diritti fondamentali delle persone."},
  {s:"Le tribunal administratif examine les recours des citoyens.",      it:"Il tribunale amministrativo esamina i ricorsi dei cittadini."},
  {s:"La Convention européenne protège les libertés individuelles.",     it:"La Convenzione europea protegge le libertà individuali."},
  {s:"Le législateur a voté le projet de loi à l'unanimité.",            it:"Il legislatore ha votato il disegno di legge all'unanimità."},
  {s:"La jurisprudence interprète les textes juridiques ambigus.",       it:"La giurisprudenza interpreta i testi giuridici ambigui."},
  {s:"Le Conseil d'État conseille le gouvernement sur les décrets.",     it:"Il Consiglio di Stato consiglia il governo sui decreti."},
  {s:"La Cour de justice de l'Union européenne siège à Luxembourg.",     it:"La Corte di giustizia dell'Unione europea ha sede a Lussemburgo."},
  {s:"Le règlement protège les données personnelles des utilisateurs.",  it:"Il regolamento protegge i dati personali degli utenti."},
  {s:"L'avocat plaide la cause de son client devant le juge.",           it:"L'avvocato difende la causa del suo cliente davanti al giudice."},
  {s:"Le contrat engage les deux parties signataires.",                  it:"Il contratto vincola le due parti firmatarie."},
  {s:"La séparation des pouvoirs garantit l'indépendance de la justice.", it:"La separazione dei poteri garantisce l'indipendenza della giustizia."},
  {s:"Les États membres ratifient le traité européen.",                  it:"Gli Stati membri ratificano il trattato europeo."},
];
const LAW_LEN = 8;

/* ---- Level 6: enter / train a custom sentence ---- */
const SENT_EXAMPLES = [
  "La liberté des uns s'arrête là où commence celle des autres.",
  "Je voudrais réserver une table pour deux personnes à vingt heures.",
  "Les grenouilles vertes coassent au bord de l'étang.",
  "Mon oncle habite un vieux village au cœur des montagnes."
];

export { LEVEL1, LEVEL2, LEVEL3, TRANS, ODD, LAW_SENTENCES, LAW_LEN, SENT_EXAMPLES };
